-- 1. Rooms Table (Host Sessions)
-- Stores custom claimed room codes bound to authenticated users
create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  code text not null unique,
  owner_id uuid references auth.users(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.rooms enable row level security;

-- Policy: Everyone can read rooms
create policy "Allow public read access" on public.rooms for select using (true);

-- Policy: Owners can update their room code
create policy "Allow owners update" on public.rooms for update using (auth.uid() = owner_id);

-- Policy: Anyone can insert (to claim anon rooms or custom codes)
create policy "Allow public insert" on public.rooms for insert with check (true);
