-- Off Key Karaoke Database Schema

-- 1. Songs Table (The Permanent Songbook)
-- Stores the library of known/saved karaoke tracks
create table public.songs (
  id bigint generated by default as identity primary key,
  song_number integer not null unique, -- The 4-digit ID (e.g. 1042)
  title text not null,
  artist text not null,
  youtube_id text not null,
  duration text, -- e.g. "3:45"
  genre text,
  decade text,
  thumbnail_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.songs enable row level security;

-- Policy: Everyone can read songs
create policy "Allow public read access" on public.songs for select using (true);

-- Policy: Only authenticated/service_role can insert (Host)
-- For now, we'll allow anon insert for demo purposes if needed, OR restrict to service role.
-- Let's allow anon insert to make the "Add to Library" feature work from the client for now.
create policy "Allow anon insert" on public.songs for insert with check (true);


-- 2. Queue Table (The Live Lineup)
-- Stores the active playlist/requests
create table public.queue (
  id bigint generated by default as identity primary key,
  song_id bigint references public.songs(id) not null,
  singer_name text not null,
  status text check (status in ('queued', 'playing', 'history', 'cancelled')) default 'queued',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Sync & Room Features
  room_code text default 'A94B',
  current_position_seconds integer default 0,
  last_sync_at timestamp with time zone default now(),
  reset_trigger_count integer default 0
);

-- Index for fast room lookups
CREATE INDEX IF NOT EXISTS idx_queue_room_code ON public.queue(room_code) WHERE status = 'playing';

-- Enable RLS
alter table public.queue enable row level security;

-- Policy: Everyone can read the queue (Host, Stage, Guests)
create policy "Allow public read access" on public.queue for select using (true);

-- Policy: Everyone can add to queue (Guests requesting songs)
create policy "Allow public insert" on public.queue for insert with check (true);

-- Policy: Allow updates (Host changing status to playing/history)
create policy "Allow public update" on public.queue for update using (true);

-- Realtime: Enable realtime for queue updates so the Host/Stage dashboards update instantly
alter publication supabase_realtime add table public.queue;

-- 3. Rooms Table (Host Sessions)
-- Stores custom claimed room codes bound to authenticated users
create table public.rooms (
  id bigint generated by default as identity primary key,
  code text not null unique,
  owner_id uuid references auth.users(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.rooms enable row level security;

-- Policy: Everyone can read rooms
create policy "Allow public read access" on public.rooms for select using (true);

-- Policy: Owners can update their room code
create policy "Allow owners update" on public.rooms for update using (auth.uid() = owner_id);

-- Policy: Anyone can insert (to claim anon rooms initially or through logic)
-- Restricting this later can ensure only logged-in users claim explicitly
create policy "Allow public insert" on public.rooms for insert with check (true);
